language: go

env:
- GO111MODULE=on

go:
- 1.12.x

notifications:
  # Don't email the results of the test runs.
  email: false

before_script:
- go get -u golang.org/x/lint/golint

script:
- go build
- go test -v -race ./...
- golint -set_exit_status ./...
- docker build .
