---
version: '3.7'
services:
  server:
    image: cachecash/watchtower-server
    command: -logLevel debug
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
    - 8080:8080
    - 4000:4000
    environment:
    - UPDATE_SERVER_DATABASE=host=db port=5432 user=postgres dbname=updates sslmode=disable

  db:
    image: postgres:11
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=updates
...
